TMPエラーの解消
Assets\TextMesh Pro\Examples & Extras\Scripts\ObjectSpin.cs(34,50): error CS1061: 'Light' does not contain a definition for 'color' and no accessible extension method 'color' accepting a first argument of type 'Light' could be found (are you missing a using directive or an assembly reference?)

というエラーに対して、Assets > TextMesh Proフォルダ内のExamples & Extrasフォルダとフォルダに含まれているデータを削除して対処しました。